package com.dongldh.carrot.util

const val DATABASE_NAME = "new_carrot_db"
const val REGION_JSON = "regions.json"

// SharedPreference
const val UID_DETACHED = "UID_DETACHED"
const val REGION_SELECTED_DETACHED = "REGION_SELECTED_DETACHED"

const val COLLECTION_USERS = "users"

const val STATE_INIT = "STATE_INIT"
const val STATE_BLANK = "STATE_BLANK"

const val ACCOUNT_ID = "ACCOUNT_ID"
const val ACCOUNT_PASSWORD = "ACCOUNT_PASSWORD"
const val ACCOUNT_NICKNAME = "ACCOUNT_NICKNAME"
const val ACCOUNT_PROFILE_IMAGE_URL = "ACCOUNT_PROFILE_IMAGE_URL"

const val ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD"
const val ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"

const val NO_REGION_DATA = -100L